estimat_beta의 작성과정
1. x의 전치행렬을 x2라는 이름으로 만들어 줍니다. 
2. x2x라는 이름으로 x2와 x를곱해줍니다
3. x2y라는 이름으로 x2와 y를 곱해줍니다. 
4. x2x_inv라는 이름으로 x2x의 역행렬을 만들어 줍니다. 
5. beta_hat이라는 이름으로 x2x와 x2x_inv를 곱해줍니다.

순서는 unit 2 다중선형회귀 Example을 참고하였습니다. 

In [85]:
import numpy as np
from numpy.linalg import inv 

def estimate_beta(x, y):
    x2 = np.transpose(x)
    x2x = np.dot(x2,x)
    x2y = np.dot(x2,y)
    x2x_inv = np.linalg.inv(x2x)
    beta_hat = np.dot(x2x_inv,x2y)
    
    return beta_hat

In [86]:
#x행렬에 intercept를 추가해야함
x = np.array([ [1, 0, 1],
               [1, 2, 3],
               [1, 3, 8]]) #3x3
y = np.transpose(np.array([1, 3, 7])) #3x1

In [87]:
x

array([[1, 0, 1],
       [1, 2, 3],
       [1, 3, 8]])

In [88]:
y

array([1, 3, 7])

In [89]:
estimate_beta(x,y)

array([0.25, 0.25, 0.75])

In [90]:
from sklearn.linear_model import LinearRegression

In [91]:
reg = LinearRegression(fit_intercept=False).fit(x, y)

In [92]:
reg.coef_

array([0.25, 0.25, 0.75])